# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Cloud Run Developer (roles/run.developer)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources
#
# 3. Change the values in the "env" block to match your values.
name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  SERVICE_NAME: bank-autoscale-demo
  REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth with service account
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Enable required APIs (idempotent)
      run: |
        gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com

    - name: Deploy to Cloud Run (build from source)
      run: |
        gcloud run deploy "$SERVICE_NAME" \
          --source . \
          --region "$REGION" \
          --allow-unauthenticated \
          --platform managed \
          --memory 256Mi \
          --concurrency 10 \
          --max-instances 10

    - name: Print Service URL
      run: |
        gcloud run services describe "$SERVICE_NAME" \
          --region "$REGION" \
          --format='value(status.url)'
